import React, { StyleSheet, Dimensions } from "react-native";
import { Device } from "../../Common";

const { width, height } = Dimensions.get("window"),
  { isIOS } = Device,
  vw = width / 100,
  vh = height / 100;

export default StyleSheet.create({
  wrap: {
    marginTop: 0.05 * height,
    marginHorizontal: vw * 3,
    marginBottom: 4,
    borderRadius: 8,
    height: vh * 60,
  },
  body: {
    borderRadius: 8,
    height: vh * 60,
    overflow: "hidden",
    backgroundColor: "rgba(255, 255, 255, 1)",
  },
  header: {
    flexDirection: "row",
    justifyContent: "center",
    position: "relative",
  },
  wrapForm: {
    flex: 1,
    paddingTop: 16,
    paddingRight: 16,
    paddingBottom: 16,
    paddingLeft: 16,
  },
  textInput: {
    borderBottomWidth: 1,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    borderBottomColor: "rgba(0,0,0, 0.2)",
    backgroundColor: "#FFF",
    height: 40,
    borderRadius: 2,
    fontSize: 15,
    color: "#333",
  },
  textInputWrap: {
    marginTop: 10,
  },
  textLabel: {
    fontSize: 12,
    color: "#333",
    fontWeight: isIOS ? "500" : "bold",
    marginVertical: 8,
  },
  btnLogInText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 13,
  },
  wrapButton: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  btnLogIn: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgb(72,194,172)",
    flex: 1,
    padding: 10,
    margin: 10,
    borderRadius: 25,
  },
  textInputIpad: {
    borderBottomWidth: 2,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    borderBottomColor: "rgba(0,0,0, 0.2)",
    backgroundColor: "#FFF",
    height: 80,
    borderRadius: 4,
    fontSize: 30,
    color: "#333",
  },
  textLabelIpad: {
    fontSize: 24,
    color: "#333",
    fontWeight: "500",
    marginBottom: 16,
    marginTop: 16,
  },
  btnLogInTextIpad: {
    color: "white",
    fontWeight: "bold",
    fontSize: 26,
  },
  btnLogInIpad: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgb(72,194,172)",
    flex: 1,
    padding: 20,
    margin: 20,
    borderRadius: 50,
  },
});
