import React, { Platform, StyleSheet, Dimensions } from "react-native";
import * as Localization from "expo-localization";

import { Constants } from "../../Common";

const { width, height } = Dimensions.get("window"),
  vw = width / 100,
  vh = height / 100,
  vmin = Math.min(vw, vh),
  vmax = Math.max(vw, vh);

export default StyleSheet.create({
  container: {
    backgroundColor: "rgba(255, 255, 255, 1)",
    flex: 1,
  },
  map: {
    flex: 0.95,
  },
  wrapButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  btnLogIn: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgb(72,194,172)",
    flex: 1,
    padding: 10,
    margin: 10,
    borderRadius: 25,
  },
  btnLogInIpad: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgb(72,194,172)",
    flex: 1,
    padding: 20,
    margin: 20,
    borderRadius: 50,
  },
  textLabel: {
    fontSize: 16,
    color: "#333",
    fontWeight: "500",
    marginBottom: 8,
    marginTop: 8,
  },
  textLabelIpad: {
    fontSize: 32,
    color: "#333",
    fontWeight: "500",
    marginBottom: 16,
    marginTop: 16,
  },
  btnLogInText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 13,
  },
  btnLogInTextIpad: {
    color: "white",
    fontWeight: "bold",
    fontSize: 26,
  },
  marker: {
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 15,
    color: "#333",
    marginTop: 3,
    marginRight: 7,
    letterSpacing: 1.5,
    lineHeight: 18,
    textAlign: "center",
    backgroundColor: "transparent",
  },
  titleIpad: {
    fontSize: 30,
    fontFamily: Constants.fontFamilyBold,
    color: "#333",
    marginTop: 6,
    marginRight: 14,
    letterSpacing: 3.0,
    lineHeight: 28,
    textAlign: "left",
    backgroundColor: "transparent",
  },
  slideInnerContainer: {
    width: width / 3 + 30,
    // height: Platform.OS === 'ios' ? width / 2 + 90 : width / 2 + 90, //2+70(90)\
    // minHeight:200,

    // marginBottom: 5,
    zIndex: 9999,
  },
  textIpad: {
    color: "#555555",
    fontSize: 20,
    paddingTop: Platform.OS === "android" ? 4 : 5,
    marginLeft: 6,
    lineHeight: 28,
    fontFamily: Constants.fontFamilyLight,
    alignSelf: "flex-start",
  },
  image: {
    resizeMode: "cover",
    flex: 1,
    borderRadius: 5,
    zIndex: 9999,
  },
  wrap: {
    marginTop: 0.05 * height,
    marginHorizontal: vw * 3,
    marginBottom: 4,
    borderRadius: 8,
    height: vh * 75,
    overflow: "hidden",
    backgroundColor: "rgba(255, 255, 255, 1)",
  },
  wrapForm: {
    flex: 1,
    paddingTop: 16,
    paddingRight: 16,
    paddingBottom: 16,
    paddingLeft: 16,
  },
  wrapText: {
    // position: 'absolute',
    left: 0,
    top: 0,
    zIndex: 9999,
    backgroundColor: "rgba(255, 255, 255, 1)",
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    elevation: 10,
    shadowColor: "#FFF",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    padding: 4,
    minHeight: 200,
    margin: 10,
    shadowOffset: { width: 0, height: -12 },
  },
  textInputWrap: {
    marginTop: 30,
  },
  //head Address
  row: {
    flexDirection: "row",
    // paddingTop: 4,
    // paddingBottom: 4,
    marginVertical: 4,
    minHeight: 10,
    paddingLeft: 4,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  label: {
    width: 80,
    paddingLeft: 12,
    paddingTop: Platform.OS === "android" ? 4 : 4,
    fontSize: 10,
    color: "#212121",
    fontFamily: Constants.fontFamilyBold,
    lineHeight: 18,
  },
  text: {
    color: "#555555",
    fontSize: 10,
    paddingTop: Platform.OS === "android" ? 4 : 5,
    marginLeft: 3,
    // lineHeight: 14,
    fontFamily: Constants.fontFamilyLight,
    alignSelf: "flex-start",
  },
  textInput: {
    backgroundColor: "#ffffff",
    fontSize: 16,
    paddingTop: 10,
    color: "#000000",
  },
  textInputIpad: {
    backgroundColor: "#ffffff",
    fontSize: 32,
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
    color: "#000000",
  },
  header: {
    backgroundColor: "#fff",
    height: "8%",
    alignItems: "center",
    flexDirection: "row",
    // marginBottom: '1%'
  },
  headerText: {
    fontSize: 20,
    letterSpacing: 1.2,
    flex: 0.95,
    justifyContent: "center",
    marginLeft: Localization.locale.slice(0, 2) === "da" ? vw * 27 : vw * 34,
    color: "#000",
    fontWeight: "bold",
  },
  trackBtn: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgb(72,194,172)",
    padding: 5,
    marginRight: 10,
    borderRadius: 25,
    height: "60%",
  },
  menuItemText: {
    fontSize: 16,
  },
  counterView: {
    flex: 0.07,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 5,
  },
  counterViewChild: {
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  counterTextLabel: {
    fontFamily: Constants.fontFamily,
  },
  counterValue: {
    fontSize: 20,
    fontWeight: "500",
  },
  reportBtnAllView: {
    alignItems: "center",
    justifyContent: "center",
  },
  btnReportAll: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgb(72,194,172)",
    padding: 10,
    margin: 10,
    borderRadius: 25,
  },
  modalHeader: {
    paddingVertical: 4,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "3%",
  },
  calloutListItem: {
    flexDirection: "column",
    marginVertical: 4,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#000",
    padding: 10,
    marginHorizontal: "12%",
    borderRadius: 5,
    marginBottom: "4%",
  },
  calloutListItemText: {
    fontSize: 12,
    fontWeight: "600",
    fontFamily: Constants.fontFamilyLight,
    alignSelf: "flex-start",
  },
  modalView: {
    borderRadius: 10,
    backgroundColor: "#f6f6f6",
    padding: "2%",
    marginHorizontal: "15%",
    height: "32%",
    top: "30%",
  },
  loaderContainer: {
    position: "absolute",
    height: height,
    width: width,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.0421)",
  },
  mapTypeContainer: {
    position: "absolute",
    zIndex: 1,
    bottom: 120,
    left: 10,
  },
  mapModebutton: {
    padding: 10,
    borderRadius: 10,
    backgroundColor: "#f6f6f6",
    zIndex: 1,
  },
  typeTextStyle: {
    fontSize: 12,
    fontWeight: "600",
    fontFamily: Constants.fontFamilyBold,
    textTransform: "capitalize",
  },
});
