export const CATEGORY_ON_SELECT = 'CATEGORY_ON_SELECT';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';

export const CONTAINERS_ARRAY="CONTAINERS_ARRAY"
