import React, { StyleSheet, Dimensions } from "react-native";
import { Constants } from "../../Common";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  flatlist: {
    marginTop: 35,
    flexDirection: "row",
    flexWrap: "wrap",
    flex: 1,
  },
  body: {
    flex: 1,
    backgroundColor: "#fff",
    paddingTop: 30,
  },
  box: {
    borderRadius: 6,
    backgroundColor: "#eee",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  content: {
    backgroundColor: "transparent",
    width: width,
    height: (height * 90) / 100,
    position: "absolute",
    top: 0,
    left: 0,
  },
  image: {
    width: width - 30,
    alignItems: "center",
    marginLeft: 15,
    height: 75,
    marginBottom: 26,
    borderRadius: 6,
    overflow: "hidden",
  },
  imageIpad: {
    width: width - 60,
    alignItems: "center",
    marginLeft: 30,
    height: 150,
    marginBottom: 60,
    borderRadius: 12,
  },
  overlay: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  titleView: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    width: "100%",
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 16,
    textAlign: "center",
    color: "white",
    fontFamily: Constants.fontFamilyBold,
  },
  titleIpad: {
    fontSize: 32,
    textAlign: "center",
    color: "white",
    fontFamily: Constants.fontFamilyBold,
  },
  containerStyle: {
    shadowColor: "#000",
    backgroundColor: "transparent",
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  containerStyleIpad: {
    shadowColor: "#000",
    backgroundColor: "transparent",
    shadowOpacity: 0.8,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 24 },
    elevation: 20,
  },
  wrapListCate: {
    paddingTop: 2,
  },
  textInput: {
    borderBottomWidth: 1,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 10,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    borderBottomColor: "rgba(0,0,0, 0.2)",
    backgroundColor: "#FFF",
    height: 40,
    borderRadius: 2,
    fontSize: 15,
    color: "#333",
    width: width - 60,
  },
  textInputIpad: {
    borderBottomWidth: 2,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 20,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 20,
    marginLeft: 0,
    borderBottomColor: "rgba(0,0,0, 0.2)",
    backgroundColor: "#FFF",
    height: 80,
    borderRadius: 4,
    fontSize: 30,
    color: "#333",
    width: width - 120,
  },
  textInputWrap: {
    marginBottom: 5,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    width: width,
    justifyContent: "space-between",
  },
  searchRem: {
    width: 40,
  },
  searchRemIpad: {
    width: 80,
  },
  horizontalLoading: {
    flex: 1,
    justifyContent: "center",
    flexDirection: "row",
    padding: 10,
  },
  header: {
    backgroundColor: "#fff",
    height: "8%",
    alignItems: "center",
    flexDirection: "row",
    marginBottom: "1%",
  },
  headerText: {
    fontSize: 20,
    letterSpacing: 1.2,
    flex: 1,
    textAlign: "center",
    color: "#000",
    fontWeight: "bold",
  },
});
